{
 "title": "OCM",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(container_memory_working_set_bytes{job=\"opentelemetry-collector\"},cluster_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "API Request Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(apiserver_request_total{resource=~\"managedclusters|managedclusteraddons|managedclustersetbindings|managedclustersets|addonplacementscores|placementdecisions|placements|manifestworks|manifestworkreplicasets|appliedmanifestworks|clusterclaims|klusterlets\",cluster_name=\"$cluster\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=~\"open-cluster-management.*\",cluster_name=\"$cluster\"}[3m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=~\"open-cluster-management.*\",cluster_name=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}