name: website

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
      - release-*

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.119.0'
      - name: build
        run: make static
